spring:
  application:
    name: Merchants
  datasource:
    url: ${yourhost}
    username: ${yourname}
    password: ${yourpassword}
  kafka:
    bootstrap-servers: ${yourhost}
    consumer:
      group-id: passbook
    listener:
      concurrency: 4

server:
  port: 9527

logging:
  level: debug
  file: merchants.log
