spring:
 application:
   name: Imooc-Passbook
 datasource:
   url: ${yourhost}
   username: ${yourname}
   password: ${yourpassword}
 kafka:
  bootstrap-servers: ${yourhost}
  consumer:
    group-id: passbook
  listener:
    concurrency: 4
 data:
  hbase:
    quorum: ${yourhost}
    rootDir:${yourHbaseRootDir}
    nodeParent: ${yourZookeeperNodeParent}
 redis:
    host: ${yourhost}
    port: ${yourport}

server:
  port: 9528

logging:
  file: imooc-passbook.log
  level: debug
