spring:
 application:
   name: Imooc-Passbook
 datasource:
   url: jdbc:mysql://localhost:3306/passbook?autoReconnect=true&serverTimezone=GMT
   username: root
   password: root
 kafka:
  bootstrap-servers: 119.23.206.146:9092
  consumer:
    group-id: passbook
  listener:
    concurrency: 4
 data:
  hbase:
    quorum: 127.0.0.1:2181
    rootDir: file:///D:/HBase/hbase-1.2.0/data
    nodeParent: /hbase
 redis:
    host: 119.23.206.146
    port: 6379

server:
  port: 9528

logging:
  file: imooc-passbook.log
  level: debug


